spring.application.name=payment-service

server.port=8083

resilience4j.circuitbreaker.instances.paymentService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50

logging.level.io.github.resilience4j=INFO